[config]
; 请勿修改此项。配置文件中的注释项不应用于记录信息，软件加载时会自动覆盖并删除。
version=2.0.0

[network]
; 软件访问的 NGA 域名。默认值为 https://bbs.nga.cn。
base_url=https://bbs.nga.cn
; 浏览器 User-Agent，填写你常用浏览器的 UA 即可。修改时请将尖括号及内部所有文本替换或删除，并确保值被反引号包裹。
ua=`<;MODIFY_ME;>`
; NGA 网站个人 Cookie 项目。修改时请将尖括号及内部所有文本替换或删除，并确保值被反引号包裹。
ngaPassportUid=`<;MODIFY_ME;>`
; NGA 网站个人 Cookie 项目。修改时请将尖括号及内部所有文本替换或删除，并确保值被反引号包裹。
ngaPassportCid=`<;MODIFY_ME;>`
; 网络并发数，理论上提高并发数可以增加下载速度。仅支持 1、2、3。若开启 enhance_ori_reply，请将此值设定为 1。默认值为 2。
thread=2
; [#56]每次下载限制新下载的大约页数。达到上限后需重新运行程序以继续下载，直至全部下载完成。允许范围为 -1（含）至 100（含）。当值为 0 或 -1 时则不限制。默认值为 100（约 100 页）。
page_download_limit=100

[post]
; [#44]是否查询用户基于 IP 的地理位置？若启用则会导致网络请求量最高增加 20 倍。默认值为 False（不启用）。
get_ip_location=False
; [#35]尝试将被引用回复的原始楼层内容补充完整。开启此功能要求同步将 thread 线程数设置为 1，且需全新拉取，否则可能会补充到未格式化的文本。默认值为 False（不启用）。
enhance_ori_reply=False
; [#122]启用在线模式以增强原始回复。开启此功能要求同步开启 enhance_ori_reply，开启后可能从网络获取被回复的楼层内容。默认值为 False（不启用）。
enhance_ori_reply_online=False
; [#58]是否使用本地表情图片资源，而不是引用在线资源。默认值为 False（不启用）。
use_local_smile_pic=False
; [#58]本地表情图片资源路径。支持绝对路径与相对路径。路径末尾需包含 /。
local_smile_pic_path=../smile/
; [#21]文件夹名是否使用帖子标题。默认值为 False。修改后仅对全新拉取的 tid 生效。
use_title_as_folder_name=False
; [#21]Markdown 文件名是否使用帖子标题。默认值为 False。修改后仅对全新拉取的 tid 生效。
use_title_as_md_file_name=False
; [#109]是否直接使用媒体文件的在线链接，而不是将媒体资源下载到本地后做本地引用。默认值为 False（不启用）。
use_network_media_url=False
; [#124]帖子媒体资源存储路径。留空或设为 '.' 时，资源将保存在与输出文件相同的目录下。默认值为 ./assets/。
assets_path=./assets/
; [#105]是否切分生成的 md 文件，并指定切分后每个文件大约包含的页数。1 页约等于 20 层。允许范围为 -1（含）至 200（含）。当值为 0 或 -1 时，不进行切分。默认值为 -1（不切分）。
split_md_file=-1
; 帖子输出目录。支持绝对路径与相对路径。默认值为 ./（当前程序所在目录）。
output_path=./

[server]
; Server 模式绑定 IP。可被 --host 参数覆盖。默认值为 0.0.0.0（所有网络接口）。
host=0.0.0.0
; Server 模式的 Basic Auth 密码。若未设置密码，Server 模式将拒绝启动。
password=`<;MODIFY_ME;>`
; Server 模式默认监听端口。可被 --port 参数覆盖。
port=8080
